import './globals.css'
import type { Metadata } from 'next'
import { Noto_Sans } from 'next/font/google'

const noto = Noto_Sans({ weight: ['300', '400', '500', '700'], style: ['normal'], subsets: ['cyrillic', 'latin'] })

export const metadata: Metadata = {
  title: 'Мій проект',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="uk">
      <body className={noto.className}>{children}</body>
    </html>
  )
}
