import { Footer } from './components/Footer/Footer';
import { Header } from './components/Header/Header';
import { Sidebar } from './components/Sidebar/Sidebar';
import './globals.css';
import styles from './layout.module.css';
import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';

const noto = Noto_Sans({ weight: ['300', '400', '500', '700'], style: ['normal'], subsets: ['cyrillic', 'latin'] });

export const metadata: Metadata = {
  title: 'Мій проект',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="uk">
      <body className={noto.className}>
        <div className={styles.wrapper}>
          <Header className={styles.header} />
          <Sidebar className={styles.sidebar} />
          <div className={styles.body}>{children}</div>
          <Footer className={styles.footer} />
        </div>

      </body>
    </html>
  );
}
